export const CARD_CREATE_REQUEST = 'CARD_CREATE_REQUEST'
export const CARD_CREATE_SUCCESS = 'CARD_CREATE_SUCCESS'
export const CARD_CREATE_FAIL = 'CARD_CREATE_FAIL'

export const CARD_GET_ALL_REQUEST = 'CARD_GET_ALL_REQUEST'
export const CARD_GET_ALL_SUCCESS = 'CARD_GET_ALL_SUCCESS'
export const CARD_GET_ALL_FAIL = 'CARD_GET_ALL_FAIL'